### ISSUE TITLE
TypeError: this.msalApplication.getAccount is not a function

### ISSUE THREAD

**Issue by bightg30098** [microsoftgraph/msgraph-sdk-javascript#303]
It raises following error since I upgrade @azure/msal-browser from 2.0.0-beta.0 to 2.0.0

![2020-07-21 111408](https://user-images.githubusercontent.com/18546096/88008818-acc41380-cb43-11ea-99b4-492a80d38135.png)

  "dependencies": {
    "@azure/msal-browser": "^2.0.0",
    "@microsoft/microsoft-graph-client": "^2.0.0",
    "msal": "^1.3.3",
  }

**Comment by ddyett** [comment]
this question is more specific for this repo https://github.com/AzureAD 

I believe in msal 2 getAccount is removed.  See this migration document.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md
